### ISSUE TITLE
Optional NatSpec custom tag standardization: Terms of Service

### ISSUE THREAD

**Issue by charmful0x** [coinbase/solidity-style-guide#18]
## About
Smart contract developers who want to bind an onchain Terms of Services to their solidity contract source code should include it within the contract's NatSpec tags, specifically using the `@custom:tos` tag.

---

## Proposal
Considering that Terms of Service can be lengthy and occupy a significant amount of data impacting the 24.5KiB contract size limit, binding an immutable ToS to a contract version within a fixed size tag can be achieved using the following formats:

#### Format
```solidity
// @custom:tos ar://ARWEAVE_HASH
```

- Total tag fixed size:  60 bytes

#### Format
```solidity
// @custom:tos ipfs://CID
```

- Total tag fixed size: 52 bytes

**Comment by wilsoncusack** [comment]
Thanks a lot! This is interesting. I don't think has come up for us yet. I have seen disclaimers in GitHub repo, would this be similar?

**Comment by charmful0x** [comment]
Yes! Basically this size-fixed custom tag can help with optimizing contract deployment costs and size limit when it comes to large embedded data

**Comment by wilsoncusack** [comment]
OK, thanks. I do not think we are going to add this right now, but I'll remember this if we have this need and consider adding then. 

Broadly I think people know they can use @custom tags and I don't want to callout one specifically unless we are taking a strong stance. 

Thanks!
