### ISSUE TITLE
Docs: additional project setup / contract references / solidity template

### ISSUE THREAD

**Issue by pegahcarter** [coinbase/solidity-style-guide#8]
IMO it's worth adding to the docs an opinion on using `node_modules` vs. `.gitmodules`, as well as the package manager used, even though they're not solidity-specific.

I would go so far as to create a template repo for the team and external developers to clone which provides the suggested formatting and, additionally, the protocol contracts.  A way to quickly have access to all L1 and L2 contracts, and the expected style in a template contract, would speed up dev process and give a standardized format to import and use deployed contracts.

For example, check out https://github.com/FraxFinance/frax-template.

**Comment by wilsoncusack** [comment]
Thanks! We specify that Forge should be used for dependency management. Forge currently uses git modules
