### ISSUE TITLE
There's no need to fear interfaces.

### ISSUE THREAD

**Issue by hbdgr** [coinbase/solidity-style-guide#9]
I strongly disagree with the recommendation to "Avoid writing interfaces," especially with the justification that it should be done because of NatSpec comments. This perspective overlooks the integral benefits interfaces bring to contract development.

1. **Enhanced Documentation**: Utilizing interfaces with NatSpec, especially through the `@inheritdoc` feature, actually enhances documentation quality and maintainability. It could keep comments relevant without redundancy, as demonstrated in OpenZeppelin example:
- [contract](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/extensions/ERC20Permit.sol#L42)
 - [interface](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/extensions/IERC20Permit.sol#L66).

2. **Improved Modularity**: Interfaces are crucial for creating modular, maintainable code. They define contracts between system components, promoting clean architecture and making large solidity codebases more manageable.

3. **Essential for Design Patterns**: Interfaces are vital for advanced design patterns like the Diamond Proxy (EIP-2535). This specific pattern, by itself enhances the organization and "style" of contracts, relies on interfaces, and demonstrates their benefits.

**Comment by 0xScratch** [comment]
Better we just use interfaces and include all those NatSpec comments in the main contract itself!

**Comment by 0xDetermination** [comment]
As an auditor, strongly agree with not siloing natspec in interfaces. The above comment is a good suggestion IMO; the vast majority of projects use interfaces so it's a bit weird and unintuitive to audit a codebase that doesn't use interfaces.

**Comment by hbdgr** [comment]
Okay, you're right, I also don't think that all comments should be moved to the interfaces. For example, more technical comments regarding the implementation itself like @dev, would certainly be better placed closer to the implementation.

My intention was more to show that the recommendation against using interfaces at all, due to natspec, is strange.

**Comment by 0xScratch** [comment]
Agreed...
But still, I would like to know the view of Coinbase, like why they thought of it this way. Maybe it is something which we didn't take a look of
Or, it's just that's how they want to implement smart contracts that are to be deployed on base. Felt it because of the last point in the `style guide` when it says that the author should be coinbase

**Comment by wilsoncusack** [comment]
We do not fear interfaces :) We just have a preference. Others are welcome to do as they wish. 

I think the biggest benefit of Interfaces is allowing a more open Pragma, which makes it easier for other devs in the future. 

Closing as we do not plan to take action here. Thanks for taking the time.
